# Generated by Django 4.2.2 on 2026-02-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_mailattempt_id_alter_mailing_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailattempt",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attempts",
                to="mailing.recipient",
            ),
        ),
    ]
