# Generated by Django 4.2.2 on 2026-02-11 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0003_mailattempt_recipient"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailing",
            old_name="start_at",
            new_name="start_time",
        ),
        migrations.RenameField(
            model_name="mailing",
            old_name="end_at",
            new_name="end_time",
        ),
    ]
