# Generated by Django 4.2.2 on 2026-02-13 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_mailing_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailattempt",
            options={"verbose_name": "Попытка отправки", "verbose_name_plural": "Попытки отправок"},
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_all_mailings", "Может просматривать все рассылки"),
                    ("can_disable_mailings", "Может отключать рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("can_view_all_messages", "Может просматривать все сообщения")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "permissions": [("can_view_all_recipients", "Может просматривать всех получателей")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
