# Generated by Django 4.2.2 on 2026-02-21 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_alter_mailattempt_options_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "default_permissions": ("add", "change", "delete", "view"),
                "permissions": [
                    ("can_view_all_mailings", "Может просматривать все рассылки"),
                    ("can_disable_mailings", "Может отключать рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
